name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        echo $(ls)
        cd /ngrok-stable-linux-amd64
        ngrok authtoken $NGROK_AUTH_TOKEN
    - name: Create Tunnel
      run: ngrok tcp --region=eu 3389
